name: Update DNF Repo with Multiple RPMs

### NOTE: schedule-strigger only run on default branch

on:  # Trigger manually or on a schedule (e.g., weekly)
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Central Repository
        uses: actions/checkout@v4
        with:
          ref: linux_rpm    # Specify the branch, default is `main`

      - name: Install createrepo
        run: sudo apt-get install -y createrepo-c

      - name: Create rpms directory if it doesn't exist
        run: mkdir -p rpms

      - name: Download RPM 1 rustdesk
        run: |
            RPM_URL=$(curl -sL https://github.com/rustdesk/rustdesk/releases/latest | grep -wo "https.*x86_64.rpm")
            RPM_FILE="rpms/rustdesk-latest.rpm"
            curl -L -o ${RPM_FILE} ${RPM_URL}

    #   - name: Download RPM from repo2
    #     run: |
    #       curl -L -o rpms/app2-latest.rpm \
    #       "https://github.com/otheruser/repo2/releases/latest/download/app2-$(curl -s https://api.github.com/repos/otheruser/repo2/releases/latest | jq -r .tag_name)-1.el8.x86_64.rpm"

      - name: Update Repository Metadata
        run: createrepo_c rpms/


      - name: Commit and Push Changes      # Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatic update latest RPMs"
