### NOTE: schedule-strigger only run on default branch
name: Update versions of .spec files

on:  # Trigger manually or on a schedule (e.g., weekly)
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Central Repository
        uses: actions/checkout@v4
        with:
          ref: copr_spec    # Specify the branch, default is `main`

    ### Update the .spec files
      - name: Update .spec files
        run: |
          bash update_spec_version.sh

    ### Update the repository
      - name: Commit and Push Changes      # Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update versions of .spec files"
